#*********************************************************************
#   Copyright 2019 Regents of the University of California
#   All rights reserved
#*********************************************************************
version: '3.7'
services:
  redis:
    container_name: redis
    image: redis
    ports:
    - published: 8086
      target: 6379
    stdin_open: true
    tty: true
